In [3]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv(Path('./Resources/ibtracs.since1980.list.v04r00.csv'))
df.head()

C:\Users\jbate\anaconda3\envs\mlenv\lib\site-packages\IPython\core\interactiveshell.py:3147: DtypeWarning: Columns (1,2,8,9,14,19,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,SID,SEASON,NUMBER,BASIN,SUBBASIN,NAME,ISO_TIME,NATURE,LAT,LON,...,TRACK_TYPE,DIST2LAND,LANDFALL,IFLAG,USA_AGENCY,USA_ATCF_ID,USA_LAT,USA_LON,STORM_SPEED,STORM_DIR
0,,Year,,,,,,,degrees_north,degrees_east,...,,km,km,,,,degrees_north,degrees_east,kts,degrees
1,1980001S13173,1980,1,SP,MM,PENI,1/1/1980 0:00,TS,-12.5,172.5,...,main,647,647,O________OO_O_,jtwc_sh,SH051980,-12.5,172.5,6,351
2,1980001S13173,1980,1,SP,MM,PENI,1/1/1980 3:00,TS,-12.1927,172.441,...,main,653,653,P________PP_P_,,SH051980,-12.1825,172.432,6,351
3,1980001S13173,1980,1,SP,MM,PENI,1/1/1980 6:00,TS,-11.9144,172.412,...,main,670,670,O________OP_O_,jtwc_sh,SH051980,-11.9,172.4,5,358
4,1980001S13173,1980,1,SP,MM,PENI,1/1/1980 9:00,TS,-11.6863,172.435,...,main,682,682,P________PP_P_,,SH051980,-11.6775,172.428,4,12